name: Docker Image CI for AI bulk video

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: zeroscope-bulkvideo-job

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup buildx
      uses: docker/setup-buildx-action@v2.9.1
    - name: Log in to the Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker Image
      uses: docker/build-push-action@v4.1.1
      with:
        context: "{{defaultContext}}:ai-video"
        push: true
        tags: hkitsmallpotato/zeroscope-bulkvideo-job:latest
